### ISSUE TITLE
Compiled scripts produce errors

### ISSUE THREAD

**Issue by relative63** [proletariatgames/HUGS#18]
error CS0200: Property or indexer `UnityEngine.Component.transform' cannot be assigned to (it is read only)

error CS0200: Property or indexer `UnityEngine.Component.rigidbody' cannot be assigned to (it is read only)

Using Unity 4.5.5.

**Comment by muguangyi** [comment]
Maybe you need check if all properties "set" operation is setting to "never" in your local Component.hx.

**Comment by relative63** [comment]
Checked my local Component.hx and it does indeed have "never" as the "set" operation. However, isn't HUGS using net libs instead of extern classes?

**Comment by relative63** [comment]
Using the net libraries (UnityEngine.dll) instead of the extern classes resolves this issue.
