### ISSUE TITLE
Latest commit has missing source files!

### ISSUE THREAD

**Issue by relative63** [proletariatgames/HUGS#19]
On the latest commit most of the entire source files are missing for unityengine, and unityeditor.

Commit: 68273b761d4ec1d9e107a2faf14739408fef74b8

**Comment by nadako** [comment]
Why is this an issue? Haxe can now load types from the .NET DLL so those extern classes are not needed anymore.

**Comment by relative63** [comment]
Ah, did not know that. Will close this out, apologies.
